// this is a read only file generated by the codegen command.
export let escrowContracts = new Map<string, string>();
escrowContracts.set('rewardEscrow-mumbai', '0x6a068aafad5095aeafc96f79d164867a29932a03');
escrowContracts.set('escrow-mumbai', '0x44b7f2effa8208ffae6613c810b1f8f89adbc102');
// this is a read only file generated by the codegen command.
